name: Tests on CI
on: [push]
jobs:

  buildGo:
    name: Building Go
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Building
      run: |
        cd go
        go build -v .

    - name: Testing
      run: |
        cd go;
        go test -v -count=1 ./...
  
  buildRust:
    name: Building Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetching Dependencies
      run: |
        cd rust
        git submodule update --init --recursive
    - name: Building
      run: |
        cd rust
        cargo build --verbose
    - name: Testing
      run: |
        cd rust
        cargo test --verbose

